before_install:
   - sudo apt-get -y update
   - sudo apt-get -y install libicu-dev libmozjs-dev pkg-config help2man libcurl4-openssl-dev
   - sudo apt-get -y install libtool automake autoconf autoconf-archive
   - sudo apt-get -y install texlive-latex-base texlive-latex-recommended
   - sudo apt-get -y install texlive-latex-extra texlive-fonts-recommended texinfo
   - sudo apt-get -y install python-pygments python-docutils python-sphinx
before_script: ./configure -c
script:
   - make check
   - cd src/fauxton
   - npm install
   - grunt test
language: erlang
otp_release:
   - 17.4
   - 17.1
   - R14B04
git:
  depth: 10
cache: apt
